# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ implementation of FFBB algorithm 
#' @keywords internal
FFBScpp <- function(lambda_mat, tau, m0 = 0.0, s0 = 0.5, delta = 0.5) {
    .Call(`_dyRank_FFBScpp`, lambda_mat, tau, m0, s0, delta)
}

#' C++ implementation of count updates 
#' @keywords internal
update_counts_cpp <- function(c_mk, dat_GP, time_GP, delta, lambda, tr) {
    .Call(`_dyRank_update_counts_cpp`, c_mk, dat_GP, time_GP, delta, lambda, tr)
}

