# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dyRank_gibbs <- function(lambda, c_mk, dat, race_attr, driver_attr, id_driver_fix, trunc) {
    invisible(.Call(`_dyRank_dyRank_gibbs`, lambda, c_mk, dat, race_attr, driver_attr, id_driver_fix, trunc))
}

dyRank_cpp <- function(lambda, c_mk, dat, race_attr, driver_attr, mcmc, burnin, thin, id_driver_fix, trunc) {
    .Call(`_dyRank_dyRank_cpp`, lambda, c_mk, dat, race_attr, driver_attr, mcmc, burnin, thin, id_driver_fix, trunc)
}

hdyRank_gibbs <- function(lambda, lambda_mean, sigma, c_mk, dat, race_attr, driver_attr, id_driver_fix, trunc) {
    invisible(.Call(`_dyRank_hdyRank_gibbs`, lambda, lambda_mean, sigma, c_mk, dat, race_attr, driver_attr, id_driver_fix, trunc))
}

hdyRank_cpp <- function(lambda, lambda_mean, sigma, c_mk, dat, race_attr, driver_attr, mcmc, burnin, thin, id_driver_fix, trunc) {
    .Call(`_dyRank_hdyRank_cpp`, lambda, lambda_mean, sigma, c_mk, dat, race_attr, driver_attr, mcmc, burnin, thin, id_driver_fix, trunc)
}

pgdraw_rcpp <- function(b, c) {
    .Call(`_dyRank_pgdraw_rcpp`, b, c)
}

samplepg <- function(z) {
    .Call(`_dyRank_samplepg`, z)
}

#' Update moments for a driver 
#' @keywords internal 
#' @param dat A matrix of one driver's information.
update_moments <- function(dat, race_attr, driver_attr, lambda, c_mk, trunc = 5L) {
    .Call(`_dyRank_update_moments`, dat, race_attr, driver_attr, lambda, c_mk, trunc)
}

update_counts <- function(dat, lambda, race_attr, driver_attr, c_mk, trunc = 5L) {
    invisible(.Call(`_dyRank_update_counts`, dat, lambda, race_attr, driver_attr, c_mk, trunc))
}

#' Initialize c_mk 
#' @return Updated c_mk.
#' @param dat A matrix 
#' @param lambda A matrix of new values of λ
#' @param race_attr A matrix of race attributes.
#' @keywords internal
initialize_counts <- function(dat, lambda, race_attr, driver_attr, n_race, trunc = 5L) {
    .Call(`_dyRank_initialize_counts`, dat, lambda, race_attr, driver_attr, n_race, trunc)
}

hdyRank_update_lambda <- function(Z, Omega, lambda_mean, Sigma, n_rank_types, driver_attr, is_fix) {
    .Call(`_dyRank_hdyRank_update_lambda`, Z, Omega, lambda_mean, Sigma, n_rank_types, driver_attr, is_fix)
}

#' FFBS for Multivariate Model
#' @keywords internal
FFBSmult_cpp <- function(lambda_mat, Sigma, is_fix, m0 = 0.0, s0 = 0.25, delta = 0.25) {
    .Call(`_dyRank_FFBSmult_cpp`, lambda_mat, Sigma, is_fix, m0, s0, delta)
}

#' Update variance-covariance matrix 
#'
#' @keywords internal
#' @param lambda_mat Observed λ matrix.
#' @param v0 Degree of freedom parameter of the inverse Wishart (prior).
#' @param S0 Scale matrix of the inverse Wishart (prior).
#' @return A single draw from the inverse Wishart distribution.
update_cov_cpp <- function(lambda_mat, lambda_mean, v0, S0) {
    .Call(`_dyRank_update_cov_cpp`, lambda_mat, lambda_mean, v0, S0)
}

#' C++ implementation of FFBB algorithm 
#' @keywords internal
FFBSsingle_cpp <- function(Z, Omega, is_fix, m0 = 0.0, s0 = 0.25, delta = 0.25) {
    .Call(`_dyRank_FFBSsingle_cpp`, Z, Omega, is_fix, m0, s0, delta)
}

